// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fksoyhlhmwbxxftyqhwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrc295aGxobXdieHhmdHlxaHdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTkwOTcsImV4cCI6MjA3MDgzNTA5N30.iePCszc-NnOYVCx1m5ri4BaQ3Hy3p1C8pOMrlUfttKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});